name: devfest
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  card_swiper : ^2.0.1
  cloud_firestore: ^4.0.2
  firebase_auth: ^4.0.2
  google_sign_in: ^5.4.1

  firebase_core: ^2.1.0
  flutter:
    sdk: flutter
 
  
  flutter_localizations:
    sdk: flutter
  flutter_phosphor_icons: ^0.0.1+6
  flutter_polyline_points: ^1.0.0
  flutter_svg: ^1.1.4
  gap: ^2.0.0
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.2.1
  google_place: ^0.4.7
  hooks_riverpod: ^1.0.4
  intl: ^0.17.0
  location: ^4.4.0
  logger: ^1.1.0
  modal_bottom_sheet: ^2.1.0
  page_transition: ^2.0.9
  shared_preferences: ^2.0.15
  http: ^0.13.5
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  flutter_lints: any

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/png/
    - assets/images/svg/

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Light.ttf
          weight: 200

        - asset: assets/fonts/ProductSans-Thin.ttf
          weight: 300

        - asset: assets/fonts/ProductSans-Regular.ttf
          weight: 400

        - asset: assets/fonts/ProductSans-Medium.ttf
          weight: 500

        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700

        - asset: assets/fonts/ProductSans-Black.ttf
          weight: 900


